### ISSUE TITLE
Cannot filter using hybrid properties

### ISSUE THREAD

**Issue by timbu** [juliotrigo/sqlalchemy-filters#22]
Sqlalchemy allows hybrid-properties on a model that can generate sql expressions, and be used in queries etc.
https://docs.sqlalchemy.org/en/latest/orm/extensions/hybrid.html

Currently, a `sqlalchemy_filters.exceptions.FieldNotFound` error is raised if we try to use them in a sqlalchemy-filters filter.

**Comment by juliotrigo** [comment]
Solved by #45
