### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Sameer-Thakur-NTT** [juliotrigo/sqlalchemy-filters#42]
Hello,
I am in the process of evaluating this library for use in one of the projects we are working on. I see the last commit was over 9 months ago. Is this library being actively maintained? If so when is the next release?
Thank you
Sameer

**Comment by pbhole** [comment]
@juliotrigo This library is useful. I understand that you might be busy in some other tasks. I have the same question as above. There are some PRs pending too.
Thanks!

**Comment by juliotrigo** [comment]
Hi both @samthakur74 and @pbhole 

This library has not been discontinued and is actively maintained. Apologies for the inactivity in the last months.

I will spend some time in the coming weeks to take care of the PRs so that we can prepare a release soon.

**Comment by pbhole** [comment]
Thanks @juliotrigo for quick reply. Glad to know that it is actively maintained.

**Comment by juliotrigo** [comment]
A few pull requests have been merged in the last days.

I'll be releasing a new version of the library in the next days.

**Comment by juliotrigo** [comment]
@samthakur74 @pbhole https://github.com/juliotrigo/sqlalchemy-filters/releases/tag/v0.11.0 has just been published.
