### ISSUE TITLE
deprecated import

### ISSUE THREAD

**Issue by xenups** [juliotrigo/sqlalchemy-filters#47]
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working from collections import Iterable, namedtuple in filters.py

**Comment by bodik** [comment]
i believe it's already resolved in new release branch which is being prepared

https://github.com/juliotrigo/sqlalchemy-filters/commit/48899e3d9ec2797e5d2a69aaa573103ef55ab8c5

**Comment by xenups** [comment]
yes ,thanks

**Comment by juliotrigo** [comment]
Hi @xenups, as @bodik said, this has been resolved in the https://github.com/juliotrigo/sqlalchemy-filters/releases/tag/v0.11.0 release that has just been published.
