### ISSUE TITLE
apply_filters with an optional OR argument

### ISSUE THREAD

**Issue by munkien** [juliotrigo/sqlalchemy-filters#70]
Hello,

In my application I really need an apply_filters OR edition
I have made a custom function for this, but would there be an interest in a PR to include this in the regular apply_filters? backwards compatible by an optional argument called "as_or" or similar?

**Comment by bodik** [comment]
I don't quite understand the issue here. I think there's a OR support already implemented https://github.com/juliotrigo/sqlalchemy-filters#boolean-functions
